name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  yarn-build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install Yarn
      run: npm install -g yarn

    - run: yarn install
      working-directory: ./web
      
    - run: yarn build
      working-directory: ./web

  go-build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build api
      working-directory: ./api
      run: go build -v ./...
    
    - name: Build vmm
      working-directory: ./vmm
      run: go build -v ./...

    - name: Build tools
      working-directory: ./tools
      run: go build -v ./...

  go-test-x86_64:
    runs-on: [self-hosted, linux, X64]
    needs: go-build
    steps:
    - name: System info
      run: df -h

    - name: Test vmm
      working-directory: ./vmm
      run: go test -v ./... -coverprofile=coverage.out
