name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [self-hosted, linux, X64]
    steps:
    - uses: actions/checkout@v2

    - name: System info
      run: df -h

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      working-directory: ./vmm
      run: go build -v ./...

    - name: Test
      working-directory: ./vmm
      run: go test -v ./... -coverprofile=coverage.out
